services:
  - type: web
    name: emo-robot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false   # you set this manually in Render dashboard
